import {
  Activity,
  ArrowRight,
  Baby,
  BadgeCheck,
  Banknote,
  BarChart3,
  Bone,
  Brain,
  Building2,
  CheckCircle2,
  ClipboardCheck,
  Droplet,
  Droplets,
  Ear,
  Eye,
  FileCheck2,
  FileText,
  GraduationCap,
  Handshake,
  HeartPulse,
  KeyRound,
  Layers,
  LayoutGrid,
  Lightbulb,
  ListChecks,
  Lock,
  Mail,
  MapPin,
  MessageSquare,
  Microscope,
  Monitor,
  PenLine,
  Phone,
  Receipt,
  Scale,
  Scan,
  Scissors,
  Send,
  ShieldAlert,
  ShieldCheck,
  Siren,
  Sparkles,
  Stethoscope,
  Target,
  TrendingUp,
  Trophy,
  UserRound,
  Users,
  Wind,
  Workflow,
  type LucideIcon,
} from "lucide-react";

/**
 * Explicit icon registry. Content files reference icons by name, so the map has
 * to be exhaustive and typed — a bad name is then a build error, not a blank
 * space on the page.
 */
const icons = {
  activity: Activity,
  arrowRight: ArrowRight,
  baby: Baby,
  badgeCheck: BadgeCheck,
  banknote: Banknote,
  barChart: BarChart3,
  bone: Bone,
  brain: Brain,
  building2: Building2,
  check: CheckCircle2,
  clipboardCheck: ClipboardCheck,
  droplet: Droplet,
  droplets: Droplets,
  ear: Ear,
  eye: Eye,
  fileCheck: FileCheck2,
  fileText: FileText,
  graduationCap: GraduationCap,
  handshake: Handshake,
  heartPulse: HeartPulse,
  keyRound: KeyRound,
  layers: Layers,
  layoutGrid: LayoutGrid,
  lightbulb: Lightbulb,
  listChecks: ListChecks,
  lock: Lock,
  mail: Mail,
  mapPin: MapPin,
  messageSquare: MessageSquare,
  microscope: Microscope,
  monitor: Monitor,
  penLine: PenLine,
  phone: Phone,
  receipt: Receipt,
  scale: Scale,
  scan: Scan,
  scissors: Scissors,
  send: Send,
  shieldAlert: ShieldAlert,
  shieldCheck: ShieldCheck,
  siren: Siren,
  sparkles: Sparkles,
  stethoscope: Stethoscope,
  target: Target,
  trendingUp: TrendingUp,
  trophy: Trophy,
  userRound: UserRound,
  users: Users,
  wind: Wind,
  workflow: Workflow,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

export function Icon({
  name,
  className,
  strokeWidth = 1.75,
}: {
  name: IconName;
  className?: string;
  strokeWidth?: number;
}) {
  const Component = icons[name];
  return <Component className={className} strokeWidth={strokeWidth} aria-hidden />;
}
